// dashboard.jsx — Neural Telemetry Command Center for male-cns:v1.0.
//
// Five-module grid: (1) Optic Flow Tunnel — a procedural closed-loop VR
// environment the connectome actually flies through, (2) real connectome
// morphology (navis skeleton fibers + soma instances), (3) a 2D ommatidia
// sensory matrix, (4) a raw-canvas spike raster, (5) RL "brain money"
// metrics (dopamine release / cumulative reward).
//
// Closed loop: tunnel wall proximity (Module 1) is piped straight into the
// backend's existing set_visual_input() pathway (the same one that already
// drives ol_sensory neurons), collisions/sustained clean flight fire the
// same real PPL/PAM DAN populations the manual "mushroom-body learning"
// panel already uses, and DN spike rates already broadcast as
// (thrust, yaw_rate) drive the tunnel camera. None of that required backend
// changes — telemetry_server.py / run_simulation.py already exposed every
// hook this needs (visual_input, set_group_drive, inject_spike, the
// per-tick thrust/yaw_rate/reward_signal/cumulative_reward broadcast).
//
// Perf rule: high-frequency (60Hz) telemetry never touches React state.
// WebSocket messages write into refs and mutate the DOM/canvas/Three.js
// objects directly; React state is reserved for things that actually
// change rarely (connection status, pause, learning toggle, slider seeds).

import { useCallback, useEffect, useImperativeHandle, useMemo, useRef, useState, forwardRef } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { Bounds, OrbitControls, PerformanceMonitor } from '@react-three/drei'
import * as THREE from 'three'

const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:8000'
const WS_URL = API_BASE.replace(/^http/, 'ws') + '/ws'
// Nodes-only sidecar (see run_simulation.py) — the dashboard never reads
// graph.edges, and on the full male-cns dataset edges are >90% of
// brain_graph.json's bytes. This sidecar is regenerated by the backend on
// every load.
const GRAPH_URL = API_BASE + '/static/brain_graph_nodes.json'

const DN_COLOR = new THREE.Color('#ff6644')
const NEURON_COLOR = new THREE.Color('#4fa3ff')
const SPIKE_COLOR = new THREE.Color('#ffffff')
// Mushroom-body learning circuit — real neuPrint `class` populations, not
// superclass (no kenyon_cell/mushroom_body superclass exists in this
// dataset — see AGENTS.md).
const KC_COLOR = new THREE.Color('#7a5fd6')
const MBON_COLOR = new THREE.Color('#d65fb0')
const DAN_COLOR = new THREE.Color('#ffcc33')
const LEARN_COLOR = new THREE.Color('#ff2fd0')
const COLOR_DECAY = 0.85
const BRAIN_SCALE = 1 / 4000

// ---------------------------------------------------------------------
// Module 2: connectome morphology (unchanged from the pure-sandbox build —
// already matches the emissive-neon-on-black spec: neon blue central
// tracts, deep green optic-lobe pathway, matrixAutoUpdate=false, LOD).
// ---------------------------------------------------------------------

function useBrainLayout(graph) {
  return useMemo(() => {
    const nodes = graph.nodes.filter((n) => n.soma[0] !== null)
    const count = nodes.length
    const positions = new Float32Array(count * 3)
    const baseColors = new Float32Array(count * 3)
    const idIndex = new Map()

    let cx = 0, cy = 0, cz = 0
    for (const n of nodes) { cx += n.soma[0]; cy += n.soma[1]; cz += n.soma[2] }
    cx /= count; cy /= count; cz /= count

    nodes.forEach((n, i) => {
      positions[i * 3 + 0] = (n.soma[0] - cx) * BRAIN_SCALE
      positions[i * 3 + 1] = -(n.soma[2] - cz) * BRAIN_SCALE
      positions[i * 3 + 2] = (n.soma[1] - cy) * BRAIN_SCALE
      const c = n.is_dn ? DN_COLOR
        : n.class === 'Kenyon_Cell' ? KC_COLOR
        : n.class === 'MBON' ? MBON_COLOR
        : n.class === 'DAN' ? DAN_COLOR
        : NEURON_COLOR
      baseColors[i * 3 + 0] = c.r
      baseColors[i * 3 + 1] = c.g
      baseColors[i * 3 + 2] = c.b
      idIndex.set(n.id, i)
    })
    return { positions, baseColors, idIndex, count }
  }, [graph])
}

const _obj3d = new THREE.Object3D()
const _tmpColor = new THREE.Color()

function BrainInstances({ layout, spikeQueueRef, plasticWeightRef }) {
  const meshRef = useRef()
  const { positions, baseColors, idIndex, count } = layout
  // Which instance indices are currently mid-flash (spiking or learning
  // overlay) and need per-frame decay. At ~176k neurons, decaying (and
  // re-uploading to the GPU) the *entire* instance-color buffer every
  // single frame — most of which never changed — is the actual source of
  // the main-thread/GPU freeze: this tracks only the handful of neurons
  // actually mid-transition, so an idle frame with no new spikes costs
  // ~0, not O(count).
  const activeRef = useRef(new Set())

  useEffect(() => {
    const mesh = meshRef.current
    if (!mesh) return
    for (let i = 0; i < count; i++) {
      _obj3d.position.set(positions[i * 3], positions[i * 3 + 1], positions[i * 3 + 2])
      _obj3d.updateMatrix()
      mesh.setMatrixAt(i, _obj3d.matrix)
      _tmpColor.setRGB(baseColors[i * 3], baseColors[i * 3 + 1], baseColors[i * 3 + 2])
      mesh.setColorAt(i, _tmpColor)
    }
    mesh.instanceMatrix.needsUpdate = true
    if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true
    mesh.matrixAutoUpdate = false
    mesh.updateMatrix()
    activeRef.current.clear()
  }, [positions, baseColors, count])

  useFrame(() => {
    const mesh = meshRef.current
    if (!mesh || !mesh.instanceColor) return
    const colors = mesh.instanceColor.array
    const active = activeRef.current
    let changed = false

    const spiking = spikeQueueRef.current
    if (spiking && spiking.length) {
      for (const bodyId of spiking) {
        const idx = idIndex.get(bodyId)
        if (idx === undefined) continue
        const b = idx * 3
        colors[b + 0] = SPIKE_COLOR.r; colors[b + 1] = SPIKE_COLOR.g; colors[b + 2] = SPIKE_COLOR.b
        active.add(idx)
      }
      spikeQueueRef.current = null
      changed = true
    }

    if (active.size) {
      for (const idx of active) {
        const b = idx * 3
        let settled = true
        for (let k = 0; k < 3; k++) {
          const base = baseColors[b + k]
          const next = base + (colors[b + k] - base) * COLOR_DECAY
          if (Math.abs(next - base) > 0.004) settled = false
          colors[b + k] = settled ? base : next
        }
        if (settled) active.delete(idx)
      }
      changed = true
    }

    const weights = plasticWeightRef && plasticWeightRef.current
    if (weights) {
      for (const key in weights) {
        const idx = idIndex.get(Number(key))
        if (idx === undefined) continue
        const amount = Math.min(1, weights[key] * 2)
        if (amount <= 0.02) continue
        const b = idx * 3
        colors[b + 0] = colors[b + 0] + (LEARN_COLOR.r - colors[b + 0]) * amount
        colors[b + 1] = colors[b + 1] + (LEARN_COLOR.g - colors[b + 1]) * amount
        colors[b + 2] = colors[b + 2] + (LEARN_COLOR.b - colors[b + 2]) * amount
        active.add(idx) // keep it decaying back toward base afterward too
      }
      changed = true
    }

    if (changed) mesh.instanceColor.needsUpdate = true
  })

  return (
    <instancedMesh ref={meshRef} args={[null, null, count]}>
      {/* subdivision 0 (20 tris) instead of 1 (80 tris) — invisible at this
          radius, 4x fewer triangles across ~176k instances. Opaque instead
          of transparent: alpha-blending against #000 was dimming every
          color toward black, which is why the brain read as "empty". */}
      <icosahedronGeometry args={[0.06, 0]} />
      <meshBasicMaterial vertexColors toneMapped={false} />
    </instancedMesh>
  )
}

function useSegmentBuffer(url) {
  const [positions, setPositions] = useState(null)
  useEffect(() => {
    let cancelled = false
    fetch(url)
      .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(new Error(r.statusText))))
      .then((buf) => { if (!cancelled) setPositions(new Float32Array(buf)) })
      .catch(() => setPositions(null))
    return () => { cancelled = true }
  }, [url])
  return positions
}

const _p0 = new THREE.Vector3()
const _p1 = new THREE.Vector3()
const _dir = new THREE.Vector3()
const _mid = new THREE.Vector3()
const _quat = new THREE.Quaternion()
const _up = new THREE.Vector3(0, 1, 0)
const _fiberObj = new THREE.Object3D()
const FIBER_COLOR = new THREE.Color('#4fd0ff')       // neon blue — central tracts (DN output fibers)
const OPTIC_FIBER_COLOR = new THREE.Color('#22e07a')  // deep neon green — optic-lobe visual pathway

function TubeFibers({ positions, radius = 0.015, color = FIBER_COLOR }) {
  const meshRef = useRef()
  const count = positions ? Math.floor(positions.length / 6) : 0

  useEffect(() => {
    const mesh = meshRef.current
    if (!mesh || !positions || count === 0) return
    for (let i = 0; i < count; i++) {
      const b = i * 6
      _p0.set(positions[b + 0], positions[b + 1], positions[b + 2])
      _p1.set(positions[b + 3], positions[b + 4], positions[b + 5])
      _dir.subVectors(_p1, _p0)
      const len = _dir.length()
      if (len < 1e-6) {
        _fiberObj.scale.set(0, 0, 0); _fiberObj.updateMatrix(); mesh.setMatrixAt(i, _fiberObj.matrix)
        continue
      }
      _dir.normalize()
      _mid.addVectors(_p0, _p1).multiplyScalar(0.5)
      _quat.setFromUnitVectors(_up, _dir)
      _fiberObj.position.copy(_mid)
      _fiberObj.quaternion.copy(_quat)
      _fiberObj.scale.set(radius, len, radius)
      _fiberObj.updateMatrix()
      mesh.setMatrixAt(i, _fiberObj.matrix)
    }
    mesh.instanceMatrix.needsUpdate = true
    mesh.computeBoundingSphere()
    mesh.matrixAutoUpdate = false
    mesh.updateMatrix()
  }, [positions, count, radius])

  if (!positions || count === 0) return null
  return (
    <instancedMesh ref={meshRef} args={[null, null, count]} frustumCulled>
      <cylinderGeometry args={[1, 1, 1, 5, 1, false]} />
      <meshBasicMaterial color={color} toneMapped={false} transparent opacity={0.8} blending={THREE.AdditiveBlending} />
    </instancedMesh>
  )
}

function useSkeletonLOD(fineUrl, coarseUrl) {
  const finePositions = useSegmentBuffer(fineUrl)
  const coarsePositions = useSegmentBuffer(coarseUrl)
  const { camera } = useThree()
  const [level, setLevel] = useState('coarse')
  const frameRef = useRef(0)

  useFrame(() => {
    frameRef.current += 1
    if (frameRef.current % 10 !== 0) return
    if (!finePositions || !coarsePositions) return
    const dist = camera.position.length()
    const want = dist < 8 ? 'fine' : 'coarse'
    if (want !== level) setLevel(want)
  })

  return (level === 'fine' ? finePositions : coarsePositions) || coarsePositions || finePositions
}

function SkeletonFibers() {
  const dnPositions = useSkeletonLOD(
    API_BASE + '/static/dn_skeleton_segments.bin',
    API_BASE + '/static/dn_skeleton_segments_coarse.bin',
  )
  const opticPositions = useSkeletonLOD(
    API_BASE + '/static/optic_skeleton_segments.bin',
    API_BASE + '/static/optic_skeleton_segments_coarse.bin',
  )
  return (
    <>
      <TubeFibers positions={dnPositions} color={FIBER_COLOR} />
      <TubeFibers positions={opticPositions} color={OPTIC_FIBER_COLOR} />
    </>
  )
}

function BrainScene({ layout, spikeQueueRef, plasticWeightRef, onDeclinePerf, onInclinePerf }) {
  return (
    <>
      <color attach="background" args={['#000000']} />
      <ambientLight intensity={0.6} />
      <Bounds fit clip observe margin={1.35}>
        <SkeletonFibers />
        <BrainInstances layout={layout} spikeQueueRef={spikeQueueRef} plasticWeightRef={plasticWeightRef} />
      </Bounds>
      {/* demand frameloop + OrbitControls: drei invalidates automatically
          on drag/zoom/damping, no extra wiring needed for the interaction
          side — only the WS-driven spike updates need a manual
          invalidate() (wired from Dashboard via Canvas's onCreated). */}
      <OrbitControls enableDamping dampingFactor={0.08} rotateSpeed={0.5} makeDefault />
      <PerformanceMonitor onDecline={onDeclinePerf} onIncline={onInclinePerf} />
    </>
  )
}

// ---------------------------------------------------------------------
// Module 1: Optic Flow Tunnel — cheap procedural closed-loop VR corridor.
// The camera IS the fly: DN thrust/yaw_rate (already broadcast by the
// backend every tick) drive it directly. Wall proximity per side feeds
// straight back into the connectome's real ol_sensory input, and
// wall contact / sustained clean flight fire the same real PPL/PAM DAN
// populations the manual mushroom-body panel drives — this is the
// STDP reward engine's actual signal source.
// ---------------------------------------------------------------------

const TUNNEL_RADIUS = 2.2
const TUNNEL_MARGIN = 0.35         // fly's effective half-width for collision
const RING_SPACING = 1.4
const N_RINGS = 40
const BARS_PER_RING = 14
const TUNNEL_LENGTH = RING_SPACING * N_RINGS
const BASE_FORWARD_SPEED = 3.0     // world units/sec at thrust=0 (idle drift)
const THRUST_FORWARD_GAIN = 6.0    // extra world units/sec at thrust=1
const LATERAL_GAIN = 2.2           // yaw_rate -> lateral velocity
const LATERAL_DAMPING = 2.5        // /sec, pulls lateral velocity toward 0
const COLLISION_BOUNCE = -0.4
const COLLISION_COOLDOWN = 0.35    // sec between aversive spikes
const REWARD_INTERVAL = 0.6        // sec between appetitive spikes while clean

const _barObj = new THREE.Object3D()
const BAR_COLOR_A = new THREE.Color('#ffffff')
const BAR_COLOR_B = new THREE.Color('#0a0a0a')

function TunnelPillars({ scrollRef }) {
  const meshRef = useRef()
  const count = N_RINGS * BARS_PER_RING

  useFrame(() => {
    const mesh = meshRef.current
    if (!mesh) return
    const scroll = scrollRef.current
    let i = 0
    for (let r = 0; r < N_RINGS; r++) {
      let z = scroll - r * RING_SPACING
      // Recycle rings that pass behind the camera (z > 0) back out to the
      // far end, keeping every ring's z in (-TUNNEL_LENGTH, 0]. (JS `%`
      // keeps the sign of the dividend, so for a small negative z this is
      // already a no-op — the previous +TUNNEL_LENGTH/%TUNNEL_LENGTH/negate
      // version instead pushed every ring but r=0 straight out past the
      // fog cutoff every frame, which is why the tunnel rendered empty.)
      z %= TUNNEL_LENGTH
      if (z > 0) z -= TUNNEL_LENGTH
      const parity = r % 2 === 0
      for (let b = 0; b < BARS_PER_RING; b++) {
        const angle = (b / BARS_PER_RING) * Math.PI * 2
        const x = Math.cos(angle) * TUNNEL_RADIUS
        const y = Math.sin(angle) * TUNNEL_RADIUS
        // Bars stay aligned to global up (no per-bar rotation) so they read
        // as true vertical stripes, matching the classic optic-flow-drum
        // stimulus rather than tilted "petals".
        _barObj.position.set(x, y, z)
        _barObj.rotation.set(0, 0, 0)
        _barObj.scale.set(1, 1, 1)
        _barObj.updateMatrix()
        mesh.setMatrixAt(i, _barObj.matrix)
        mesh.setColorAt(i, parity ? BAR_COLOR_A : BAR_COLOR_B)
        i++
      }
    }
    mesh.instanceMatrix.needsUpdate = true
    if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true
  })

  return (
    <instancedMesh ref={meshRef} args={[null, null, count]} frustumCulled={false}>
      <boxGeometry args={[0.16, 0.9, 0.16]} />
      <meshBasicMaterial vertexColors toneMapped={false} />
    </instancedMesh>
  )
}

function TunnelRig({ flightCmdRef, telemetryRef, sendCmd, pplIds, pamIds }) {
  const scrollRef = useRef(0)
  const lateralRef = useRef(0)
  const lateralVelRef = useRef(0)
  const cooldownRef = useRef(0)
  const cleanTimerRef = useRef(0)
  const sendThrottleRef = useRef(0)

  useFrame(({ camera }, delta) => {
    const dt = Math.min(delta, 0.05)
    const cmd = flightCmdRef.current

    scrollRef.current += (BASE_FORWARD_SPEED + THRUST_FORWARD_GAIN * Math.max(0, cmd.thrust)) * dt

    lateralVelRef.current += cmd.yaw_rate * LATERAL_GAIN * dt
    lateralVelRef.current -= lateralVelRef.current * Math.min(1, LATERAL_DAMPING * dt)
    lateralRef.current += lateralVelRef.current * dt

    const limit = TUNNEL_RADIUS - TUNNEL_MARGIN
    let collided = false
    if (lateralRef.current > limit) {
      lateralRef.current = limit; lateralVelRef.current *= COLLISION_BOUNCE; collided = true
    } else if (lateralRef.current < -limit) {
      lateralRef.current = -limit; lateralVelRef.current *= COLLISION_BOUNCE; collided = true
    }

    camera.position.x = lateralRef.current
    camera.position.y = 0
    camera.rotation.z = THREE.MathUtils.clamp(-cmd.yaw_rate * 0.15, -0.4, 0.4)

    // Sensory hook: proximity to each wall -> real ol_sensory brightness.
    const proxRight = Math.max(0, lateralRef.current / limit)
    const proxLeft = Math.max(0, -lateralRef.current / limit)
    telemetryRef.current.proxLeft = proxLeft
    telemetryRef.current.proxRight = proxRight
    telemetryRef.current.collided = collided

    sendThrottleRef.current += dt
    if (sendThrottleRef.current >= 1 / 20) {
      sendThrottleRef.current = 0
      sendCmd({ cmd: 'visual_input', left: 0.25 + proxLeft * 0.75, right: 0.25 + proxRight * 0.75 })
    }

    // STDP reward engine: real PPL (aversive) on collision, real PAM
    // (appetitive) on sustained clean forward flight.
    cooldownRef.current = Math.max(0, cooldownRef.current - dt)
    if (collided) {
      cleanTimerRef.current = 0
      telemetryRef.current.collisionCount += 1
      if (cooldownRef.current <= 0 && pplIds.length) {
        cooldownRef.current = COLLISION_COOLDOWN
        sendCmd({ cmd: 'inject_spike', body_ids: pplIds })
      }
    } else if (cmd.thrust > 0.15) {
      cleanTimerRef.current += dt
      if (cleanTimerRef.current >= REWARD_INTERVAL && pamIds.length) {
        cleanTimerRef.current = 0
        sendCmd({ cmd: 'inject_spike', body_ids: samplePlain(pamIds, 40) })
      }
    } else {
      cleanTimerRef.current = 0
    }
  })

  return <TunnelPillars scrollRef={scrollRef} />
}

function samplePlain(ids, n) {
  if (ids.length <= n) return ids
  const out = []; const used = new Set()
  while (out.length < n) {
    const i = Math.floor(Math.random() * ids.length)
    if (used.has(i)) continue
    used.add(i); out.push(ids[i])
  }
  return out
}

function TunnelScene({ flightCmdRef, telemetryRef, sendCmd, pplIds, pamIds, onDeclinePerf, onInclinePerf }) {
  return (
    <>
      <color attach="background" args={['#000000']} />
      <fog attach="fog" args={['#000000', 4, 14]} />
      <TunnelRig flightCmdRef={flightCmdRef} telemetryRef={telemetryRef} sendCmd={sendCmd} pplIds={pplIds} pamIds={pamIds} />
      {/* Tunnel scrolls continuously — stays frameloop="always", so this
          just guards DPR under sustained load rather than idle-render cost. */}
      <PerformanceMonitor onDecline={onDeclinePerf} onIncline={onInclinePerf} />
    </>
  )
}

// ---------------------------------------------------------------------
// Module 3: Sensory Matrix Array — L/R ommatidia grid, driven purely by
// direct canvas mutation from telemetryRef (proxLeft/proxRight), never
// through React state.
// ---------------------------------------------------------------------

const OMMATIDIA_COLS = 9
const OMMATIDIA_ROWS = 9

function SensoryMatrix({ telemetryRef }) {
  const canvasRef = useRef()
  const containerRef = useRef()

  useEffect(() => {
    const canvas = canvasRef.current
    const container = containerRef.current
    if (!canvas || !container) return
    let raf

    const resize = () => {
      canvas.width = container.clientWidth
      canvas.height = container.clientHeight
    }
    resize()
    const ro = new ResizeObserver(resize)
    ro.observe(container)

    const ctx = canvas.getContext('2d')
    const draw = () => {
      raf = requestAnimationFrame(draw)
      const w = canvas.width, h = canvas.height
      ctx.fillStyle = '#050505'
      ctx.fillRect(0, 0, w, h)

      const { proxLeft = 0, proxRight = 0 } = telemetryRef.current
      const eyeW = w / 2
      drawEye(ctx, 0, 0, eyeW, h, proxLeft, '#4fd0ff')
      drawEye(ctx, eyeW, 0, eyeW, h, proxRight, '#22e07a')

      ctx.strokeStyle = '#1a1a1a'
      ctx.beginPath(); ctx.moveTo(eyeW, 0); ctx.lineTo(eyeW, h); ctx.stroke()
    }
    draw()
    return () => { cancelAnimationFrame(raf); ro.disconnect() }
  }, [telemetryRef])

  return (
    <div ref={containerRef} className="module-canvas-wrap">
      <canvas ref={canvasRef} />
    </div>
  )
}

function drawEye(ctx, ox, oy, w, h, proximity, colorHex) {
  const pad = Math.min(w, h) * 0.08
  const cellW = (w - pad * 2) / OMMATIDIA_COLS
  const cellH = (h - pad * 2) / OMMATIDIA_ROWS
  const r = Math.min(cellW, cellH) * 0.32
  for (let row = 0; row < OMMATIDIA_ROWS; row++) {
    for (let col = 0; col < OMMATIDIA_COLS; col++) {
      const cx = ox + pad + cellW * (col + 0.5)
      const cy = oy + pad + cellH * (row + 0.5)
      // radial falloff so activation reads as "looking at a near wall"
      const dx = (col - (OMMATIDIA_COLS - 1) / 2) / OMMATIDIA_COLS
      const dy = (row - (OMMATIDIA_ROWS - 1) / 2) / OMMATIDIA_ROWS
      const falloff = 1 - Math.min(1, Math.hypot(dx, dy) * 1.4)
      const activation = Math.max(0.06, proximity * falloff)
      ctx.beginPath()
      ctx.arc(cx, cy, r, 0, Math.PI * 2)
      ctx.fillStyle = colorHex
      ctx.globalAlpha = activation
      ctx.fill()
    }
  }
  ctx.globalAlpha = 1
}

// ---------------------------------------------------------------------
// Module 4: High-performance raster plot — raw <canvas>, no SVG/charting
// lib. A curated row set (DN L/R, optic L/R, KC, MBON, PAM, PPL) is built
// once from the graph; Dashboard calls ref.pushTick(spikingIds) directly
// from the WebSocket handler at broadcast rate (60Hz), which scrolls the
// canvas one column and stamps tick marks — no React re-render involved.
// ---------------------------------------------------------------------

const RASTER_ROW_SPECS = [
  { label: 'DN·L', color: '#ff6644', match: (n) => n.is_dn && n.soma_side === 'L', n: 14 },
  { label: 'DN·R', color: '#ff6644', match: (n) => n.is_dn && n.soma_side === 'R', n: 14 },
  { label: 'optic·L', color: '#4fd0ff', match: (n) => n.superclass === 'ol_sensory' && n.soma_side === 'L', n: 10 },
  { label: 'optic·R', color: '#4fd0ff', match: (n) => n.superclass === 'ol_sensory' && n.soma_side === 'R', n: 10 },
  { label: 'KC', color: '#7a5fd6', match: (n) => n.class === 'Kenyon_Cell', n: 10 },
  { label: 'MBON', color: '#d65fb0', match: (n) => n.class === 'MBON', n: 10 },
  { label: 'PAM', color: '#ffcc33', match: (n) => n.class === 'DAN' && (n.type || '').startsWith('PAM'), n: 6 },
  { label: 'PPL', color: '#ffcc33', match: (n) => n.class === 'DAN' && (n.type || '').startsWith('PPL'), n: 6 },
]

function useRasterRows(graph) {
  return useMemo(() => {
    const rows = []
    const idToRow = new Map()
    for (const spec of RASTER_ROW_SPECS) {
      const ids = graph.nodes.filter(spec.match).map((n) => n.id)
      const sample = ids.length > spec.n ? samplePlain(ids, spec.n) : ids
      const startRow = rows.length
      for (const id of sample) { idToRow.set(id, rows.length); rows.push({ color: spec.color }) }
      rows.push({ divider: true, label: spec.label, startRow })
    }
    return { rows, idToRow }
  }, [graph])
}

const RasterPlot = forwardRef(function RasterPlot({ rasterRows }, ref) {
  const canvasRef = useRef()
  const containerRef = useRef()
  const stateRef = useRef({ ctx: null, w: 0, h: 0, rowH: 0, col: 0 })

  useEffect(() => {
    const canvas = canvasRef.current
    const container = containerRef.current
    if (!canvas || !container) return
    const resize = () => {
      canvas.width = container.clientWidth
      canvas.height = container.clientHeight
      const ctx = canvas.getContext('2d')
      ctx.fillStyle = '#050505'
      ctx.fillRect(0, 0, canvas.width, canvas.height)
      const nRows = Math.max(1, rasterRows.rows.filter((r) => !r.divider).length)
      stateRef.current = { ctx, w: canvas.width, h: canvas.height, rowH: canvas.height / nRows, col: 0 }
    }
    resize()
    const ro = new ResizeObserver(resize)
    ro.observe(container)
    return () => ro.disconnect()
  }, [rasterRows])

  useImperativeHandle(ref, () => ({
    pushTick(spikingIds) {
      const s = stateRef.current
      if (!s.ctx) return
      const { ctx, w, h, rowH } = s
      // scroll one column left, then clear the freed rightmost column
      ctx.drawImage(canvasRef.current, 1, 0, w - 1, h, 0, 0, w - 1, h)
      ctx.fillStyle = '#050505'
      ctx.fillRect(w - 1, 0, 1, h)
      if (spikingIds && spikingIds.length) {
        for (const id of spikingIds) {
          const row = rasterRows.idToRow.get(id)
          if (row === undefined) continue
          const rowInfo = rasterRows.rows[row]
          ctx.fillStyle = rowInfo.color
          ctx.fillRect(w - 1, Math.floor(row * rowH), 1, Math.max(1, Math.ceil(rowH)))
        }
      }
    },
  }), [rasterRows])

  return (
    <div ref={containerRef} className="module-canvas-wrap">
      <canvas ref={canvasRef} />
    </div>
  )
})

// ---------------------------------------------------------------------
// Module 5: RL "brain money" metrics — cumulative reward (integral of the
// signed PAM-minus-PPL dopamine EMA) and instantaneous MBON dopamine
// release, both already computed server-side (reward_signal /
// cumulative_reward). Drawn on a raw canvas, pushed directly from the
// WebSocket handler — no chart library, no React state.
// ---------------------------------------------------------------------

const RLMetrics = forwardRef(function RLMetrics(_props, ref) {
  const canvasRef = useRef()
  const containerRef = useRef()
  const bufRef = useRef({ dopamine: [], cumulative: [], max: 256 })

  useEffect(() => {
    const canvas = canvasRef.current
    const container = containerRef.current
    if (!canvas || !container) return
    const resize = () => {
      canvas.width = container.clientWidth
      canvas.height = container.clientHeight
      redraw()
    }
    const redraw = () => {
      const ctx = canvas.getContext('2d')
      const { width: w, height: h } = canvas
      ctx.fillStyle = '#050505'
      ctx.fillRect(0, 0, w, h)
      const halfH = h / 2
      drawSeries(ctx, bufRef.current.dopamine, 0, halfH - 10, w, '#ffcc33', true, 'MBON dopamine release')
      drawSeries(ctx, bufRef.current.cumulative, halfH + 10, halfH - 10, w, '#4fa3ff', false, 'cumulative reward')
      ctx.strokeStyle = '#1a1a1a'
      ctx.beginPath(); ctx.moveTo(0, halfH); ctx.lineTo(w, halfH); ctx.stroke()
    }
    resize()
    const ro = new ResizeObserver(resize)
    ro.observe(container)
    canvas._redraw = redraw
    return () => ro.disconnect()
  }, [])

  useImperativeHandle(ref, () => ({
    pushSample(dopamine, cumulative) {
      const b = bufRef.current
      b.dopamine.push(dopamine); if (b.dopamine.length > b.max) b.dopamine.shift()
      b.cumulative.push(cumulative); if (b.cumulative.length > b.max) b.cumulative.shift()
      if (canvasRef.current && canvasRef.current._redraw) canvasRef.current._redraw()
    },
  }), [])

  return (
    <div ref={containerRef} className="module-canvas-wrap">
      <canvas ref={canvasRef} />
    </div>
  )
})

function drawSeries(ctx, data, top, height, width, colorHex, zeroCentered, label) {
  ctx.fillStyle = '#7a8494'
  ctx.font = '11px monospace'
  ctx.fillText(label, 8, top + 14)
  if (data.length < 2) return
  let lo = Math.min(...data), hi = Math.max(...data)
  if (zeroCentered) { const m = Math.max(Math.abs(lo), Math.abs(hi), 1e-6); lo = -m; hi = m }
  if (hi - lo < 1e-9) { hi = lo + 1 }
  const stepX = width / (data.length - 1)
  ctx.strokeStyle = colorHex
  ctx.lineWidth = 1.5
  ctx.beginPath()
  data.forEach((v, i) => {
    const x = i * stepX
    const y = top + height - ((v - lo) / (hi - lo)) * height
    if (i === 0) ctx.moveTo(x, y); else ctx.lineTo(x, y)
  })
  ctx.stroke()
  const last = data[data.length - 1]
  ctx.fillStyle = colorHex
  ctx.font = '11px monospace'
  ctx.fillText(last.toFixed(3), width - 60, top + 14)
}

// ---------------------------------------------------------------------
// Sensory manipulation panel (manual override) — real neuPrint populations,
// unchanged from the sandbox build.
// ---------------------------------------------------------------------

const SENSORY_CHANNELS = [
  { key: 'optic_L', label: 'Optic lobe · L', match: (n) => n.superclass === 'ol_sensory' && n.soma_side === 'L' },
  { key: 'optic_R', label: 'Optic lobe · R', match: (n) => n.superclass === 'ol_sensory' && n.soma_side === 'R' },
  { key: 'antennal', label: "Antennal (Johnston's Organ)", match: (n) => (n.type || '').startsWith('JO') },
  { key: 'olfactory', label: 'Olfactory (ORN)', match: (n) => n.type === 'ORN' },
  { key: 'leg_body', label: 'Leg / body mechanoreceptors', match: (n) => n.superclass === 'vnc_sensory' },
]

function SensoryPanel({ graph, sendCmd, groupDrive }) {
  const [local, setLocal] = useState({})
  useEffect(() => { if (groupDrive) setLocal(groupDrive) }, [groupDrive])

  const idsByChannel = useMemo(() => {
    const out = {}
    for (const ch of SENSORY_CHANNELS) out[ch.key] = graph.nodes.filter(ch.match).map((n) => n.id)
    return out
  }, [graph])

  return (
    <div className="panel floating sensory-panel">
      <div className="title">sensory manipulation</div>
      {SENSORY_CHANNELS.map((ch) => {
        const ids = idsByChannel[ch.key]
        const rate = local[ch.key] ?? 0
        return (
          <div key={ch.key} className="control-row">
            <div style={{ marginBottom: 4 }}>{ch.label} <span style={{ opacity: 0.6 }}>({ids.length})</span></div>
            <div className="control-row buttons" style={{ marginBottom: 6 }}>
              <button
                className="btn" disabled={!ids.length}
                onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: samplePlain(ids, 60) })}
              >
                spike
              </button>
            </div>
            <label className="slider-label">
              continuous drive: {rate.toFixed(2)}
              <input
                type="range" min="0" max="3" step="0.05" value={rate}
                onChange={(e) => {
                  const v = parseFloat(e.target.value)
                  setLocal((s) => ({ ...s, [ch.key]: v }))
                  sendCmd({ cmd: 'set_group_drive', group: ch.key, rate: v })
                }}
              />
            </label>
          </div>
        )
      })}
    </div>
  )
}

function ControlPanel({ graph, sendCmd, paused, sensoryDrive, noiseStd, connected, learningEnabled }) {
  const [localDrive, setLocalDrive] = useState(1.0)
  const [localNoise, setLocalNoise] = useState(0.0)

  useEffect(() => { if (sensoryDrive !== null) setLocalDrive(sensoryDrive) }, [sensoryDrive])
  useEffect(() => { if (noiseStd !== null) setLocalNoise(noiseStd) }, [noiseStd])

  const dnLeftIds = useMemo(() => graph.nodes.filter((n) => n.is_dn && n.soma_side === 'L').map((n) => n.id), [graph])
  const dnRightIds = useMemo(() => graph.nodes.filter((n) => n.is_dn && n.soma_side === 'R').map((n) => n.id), [graph])
  const sensoryIds = useMemo(() => graph.nodes.filter((n) => (n.superclass || '').includes('sensory')).map((n) => n.id), [graph])
  const pplIds = useMemo(() => graph.nodes.filter((n) => n.class === 'DAN' && (n.type || '').startsWith('PPL')).map((n) => n.id), [graph])
  const pamIds = useMemo(() => graph.nodes.filter((n) => n.class === 'DAN' && (n.type || '').startsWith('PAM')).map((n) => n.id), [graph])

  return (
    <div className="panel floating control-panel">
      <div className="title">brain controls</div>
      <div className="control-row">
        <button className={connected ? 'btn ok' : 'btn bad'} disabled>
          {connected ? '● connected' : '○ disconnected'}
        </button>
      </div>
      <div className="control-row buttons">
        <button className="btn primary" onClick={() => sendCmd({ cmd: paused ? 'resume' : 'pause' })}>
          {paused ? '▶ resume' : '⏸ pause'}
        </button>
        <button className="btn" onClick={() => sendCmd({ cmd: 'reset' })}>⟲ reset flight</button>
      </div>
      <label className="slider-label">
        sensory drive: {localDrive.toFixed(2)}
        <input type="range" min="0" max="3" step="0.05" value={localDrive}
          onChange={(e) => { const v = parseFloat(e.target.value); setLocalDrive(v); sendCmd({ cmd: 'set_params', sensory_drive: v }) }} />
      </label>
      <label className="slider-label">
        noise σ: {localNoise.toFixed(2)}
        <input type="range" min="0" max="1.5" step="0.02" value={localNoise}
          onChange={(e) => { const v = parseFloat(e.target.value); setLocalNoise(v); sendCmd({ cmd: 'set_params', noise_std: v }) }} />
      </label>
      <div className="control-row buttons">
        <button className="btn" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: samplePlain(sensoryIds, 80) })}>stimulate sensory</button>
      </div>
      <div className="control-row buttons">
        <button className="btn dn-left" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: samplePlain(dnLeftIds, 40) })}>fire DN · L</button>
        <button className="btn dn-right" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: samplePlain(dnRightIds, 40) })}>fire DN · R</button>
      </div>
      <div className="title" style={{ marginTop: 10 }}>mushroom-body learning (KC→MBON)</div>
      <div className="control-row buttons">
        <button
          className={learningEnabled ? 'btn ok' : 'btn'}
          onClick={() => sendCmd({ cmd: 'set_learning', enabled: !learningEnabled })}
        >
          {learningEnabled ? '● learning ON — click to freeze' : '○ learning off — click to enable'}
        </button>
      </div>
      <div className="control-row buttons">
        <button className="btn dn-left" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: pplIds })}>
          fire PPL (aversive)
        </button>
        <button className="btn dn-right" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: samplePlain(pamIds, 60) })}>
          fire PAM (appetitive)
        </button>
      </div>
    </div>
  )
}

// ---------------------------------------------------------------------
// Main dashboard: strict 5-module 100vh grid.
// ---------------------------------------------------------------------

export default function Dashboard() {
  const [graph, setGraph] = useState(null)
  const [error, setError] = useState(null)
  const [connected, setConnected] = useState(false)
  // Low-frequency UI state only — never written from the 60Hz tick path
  // unless the value actually changed (see ws.onmessage below).
  const [uiState, setUiState] = useState({
    paused: false, sensoryDrive: null, noiseStd: null,
    learningEnabled: false, groupDrive: null, _groupDriveStr: null,
  })
  // DPR ceiling per canvas — starts at the 1.5 cap, PerformanceMonitor
  // (in BrainScene/TunnelScene) drops it to 1 under sustained frame drops
  // and restores it once the GPU catches back up. Changes rarely (a few
  // times a session at most), so plain useState is fine here.
  const [brainDpr, setBrainDpr] = useState(1.5)
  const [tunnelDpr, setTunnelDpr] = useState(1.5)

  const spikeQueueRef = useRef(null)
  const wsRef = useRef(null)
  const flightCmdRef = useRef({ thrust: 0.5, yaw_rate: 0 })
  const plasticWeightRef = useRef(null)
  const telemetryRef = useRef({ proxLeft: 0, proxRight: 0, collided: false, collisionCount: 0 })
  const rasterRef = useRef(null)
  const rlMetricsRef = useRef(null)
  // Module 2 runs frameloop="demand" (it's otherwise static — nothing to
  // gain rendering it 60x/sec when the sim is paused or disconnected).
  // Captured from the brain Canvas's onCreated; called manually below
  // whenever a WS message actually carries something for it to draw.
  // OrbitControls drag/zoom/damping invalidates on its own (drei handles
  // that internally under demand frameloop) — this only covers the
  // WS-driven half.
  const brainInvalidateRef = useRef(() => {})

  // Direct-DOM HUD refs — updated every WS message without ever touching
  // React state (the CRITICAL RULE: no useState for 60Hz data).
  const hudRefs = useRef({})
  const setHud = useCallback((key) => (el) => { hudRefs.current[key] = el }, [])

  useEffect(() => {
    fetch(GRAPH_URL)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`${r.status} ${r.statusText}`))))
      .then(setGraph)
      .catch((e) => setError(`Failed to load brain_graph.json from ${GRAPH_URL}: ${e.message}`))
  }, [])

  const sendCmd = useCallback((cmd) => {
    const ws = wsRef.current
    if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(cmd))
  }, [])

  useEffect(() => {
    let ws, retryTimer, closedByUs = false
    const connect = () => {
      ws = new WebSocket(WS_URL)
      wsRef.current = ws
      ws.onopen = () => setConnected(true)
      ws.onclose = () => { setConnected(false); if (!closedByUs) retryTimer = setTimeout(connect, 1500) }
      ws.onerror = () => ws.close()
      ws.onmessage = (evt) => {
        const d = JSON.parse(evt.data)
        spikeQueueRef.current = d.spiking_ids
        flightCmdRef.current = { thrust: d.thrust, yaw_rate: d.yaw_rate }
        if (d.plastic_weight_changes) plasticWeightRef.current = d.plastic_weight_changes

        const h = hudRefs.current
        if (h.t) h.t.textContent = d.t.toFixed(3)
        if (h.thrust) h.thrust.textContent = d.thrust.toFixed(2)
        if (h.yaw) h.yaw.textContent = d.yaw_rate.toFixed(2)
        if (h.dnLeft) h.dnLeft.textContent = (d.dn_left_rate ?? 0).toFixed(1)
        if (h.dnRight) h.dnRight.textContent = (d.dn_right_rate ?? 0).toFixed(1)
        if (h.spiking) h.spiking.textContent = d.spiking_ids.length
        if (h.collisions) h.collisions.textContent = telemetryRef.current.collisionCount
        if (h.reward) h.reward.textContent = (d.reward_signal ?? 0).toFixed(3)
        if (h.cumulative) h.cumulative.textContent = (d.cumulative_reward ?? 0).toFixed(2)

        if (rasterRef.current) rasterRef.current.pushTick(d.spiking_ids)
        if (rlMetricsRef.current) rlMetricsRef.current.pushSample(d.reward_signal ?? 0, d.cumulative_reward ?? 0)

        // Module 2 is frameloop="demand" — nudge it to actually draw this
        // tick's spikes/plasticity now that the refs above are updated.
        if (d.spiking_ids.length || d.plastic_weight_changes) brainInvalidateRef.current()

        setUiState((prev) => {
          // group_drive arrives as a fresh object from JSON.parse on every
          // single message, so comparing it by reference (as the previous
          // version of this dedup did) was ALWAYS unequal — that was the
          // real 60Hz setState loop causing "Maximum update depth
          // exceeded", not the WS listener or raster per se. Compare its
          // serialized content instead (it's a ~5-key object, trivial to
          // stringify) so this only actually re-renders when a value
          // genuinely changes.
          const groupDriveStr = d.group_drive ? JSON.stringify(d.group_drive) : null
          if (
            !!d.paused === prev.paused &&
            (d.sensory_drive ?? null) === prev.sensoryDrive &&
            (d.noise_std ?? null) === prev.noiseStd &&
            !!d.learning_enabled === prev.learningEnabled &&
            groupDriveStr === prev._groupDriveStr
          ) return prev
          return {
            paused: !!d.paused,
            sensoryDrive: d.sensory_drive ?? null,
            noiseStd: d.noise_std ?? null,
            learningEnabled: !!d.learning_enabled,
            groupDrive: d.group_drive ?? null,
            _groupDriveStr: groupDriveStr,
          }
        })
      }
    }
    connect()
    return () => { closedByUs = true; clearTimeout(retryTimer); ws?.close() }
  }, [])

  const layout = useBrainLayout(graph ?? { nodes: [], edges: [] })
  const rasterRows = useRasterRows(graph ?? { nodes: [] })
  const pplIds = useMemo(() => (graph ? graph.nodes.filter((n) => n.class === 'DAN' && (n.type || '').startsWith('PPL')).map((n) => n.id) : []), [graph])
  const pamIds = useMemo(() => (graph ? graph.nodes.filter((n) => n.class === 'DAN' && (n.type || '').startsWith('PAM')).map((n) => n.id) : []), [graph])

  if (error) return <div className="panel error">{error}</div>
  if (!graph) return <div className="panel">Loading brain_graph.json...</div>

  return (
    <div className="dashboard-root">
      {/* MODULE 1 — Optic Flow Tunnel (closed-loop VR environment) */}
      <div className="module module-1">
        {/* Tunnel keeps frameloop="always" (default) — it's a continuous
            scroll animation, nothing to gain from demand rendering here.
            DPR is still capped to protect fill-rate on 4K/Retina panels. */}
        <Canvas dpr={[1, tunnelDpr]} camera={{ fov: 70, position: [0, 0, 0], near: 0.05, far: 20 }}>
          <TunnelScene
            flightCmdRef={flightCmdRef} telemetryRef={telemetryRef} sendCmd={sendCmd} pplIds={pplIds} pamIds={pamIds}
            onDeclinePerf={() => setTunnelDpr(1)} onInclinePerf={() => setTunnelDpr(1.5)}
          />
        </Canvas>
        <div className="panel floating module-hud">
          <div className="title">optic flow tunnel</div>
          <div>t = <span ref={setHud('t')}>0.000</span>s</div>
          <div>thrust <span ref={setHud('thrust')}>0.00</span> · yaw <span ref={setHud('yaw')}>0.00</span></div>
          <div>DN·L <span ref={setHud('dnLeft')}>0.0</span>Hz · DN·R <span ref={setHud('dnRight')}>0.0</span>Hz</div>
          <div>spiking: <span ref={setHud('spiking')}>0</span> · collisions: <span ref={setHud('collisions')}>0</span></div>
        </div>
        <ControlPanel
          graph={graph} sendCmd={sendCmd} paused={uiState.paused}
          sensoryDrive={uiState.sensoryDrive} noiseStd={uiState.noiseStd} connected={connected}
          learningEnabled={uiState.learningEnabled}
        />
      </div>

      {/* MODULE 2 — 3D volumetric connectome morphology */}
      <div className="module module-2">
        {/* frameloop="demand": this canvas is otherwise static between
            spikes/plasticity updates and OrbitControls interaction, so
            there's no reason to render it 60x/sec unconditionally — see
            brainInvalidateRef wiring in the WS handler above. */}
        <Canvas
          dpr={[1, brainDpr]} frameloop="demand" camera={{ position: [0, 0, 6], fov: 50 }}
          onCreated={(state) => { brainInvalidateRef.current = state.invalidate }}
        >
          <BrainScene
            layout={layout} spikeQueueRef={spikeQueueRef} plasticWeightRef={plasticWeightRef}
            onDeclinePerf={() => setBrainDpr(1)} onInclinePerf={() => setBrainDpr(1.5)}
          />
        </Canvas>
        <div className="panel floating module-hud small">
          <div className="title">male-cns:v1.0 — {graph.meta.node_count.toLocaleString()} neurons</div>
          <div>DNs: {graph.meta.dn_count.toLocaleString()} · edges: {graph.meta.edge_count.toLocaleString()}</div>
        </div>
        <SensoryPanel graph={graph} sendCmd={sendCmd} groupDrive={uiState.groupDrive} />
      </div>

      {/* MODULE 3 — Sensory Matrix Array (ommatidia) */}
      <div className="module module-3">
        <div className="module-label">sensory matrix — L / R ommatidia</div>
        <SensoryMatrix telemetryRef={telemetryRef} />
      </div>

      {/* MODULE 4 — High-performance spike raster */}
      <div className="module module-4">
        <div className="module-label">spike raster — DN · optic · KC · MBON · PAM/PPL</div>
        <RasterPlot ref={rasterRef} rasterRows={rasterRows} />
      </div>

      {/* MODULE 5 — RL "brain money" metrics */}
      <div className="module module-5">
        <div className="module-label">
          dopamine release: <span ref={setHud('reward')}>0.000</span> ·
          cumulative reward: <span ref={setHud('cumulative')}>0.00</span>
        </div>
        <RLMetrics ref={rlMetricsRef} />
      </div>
    </div>
  )
}
