// dashboard.jsx — Vision-first flight navigation dashboard.
//
// Architecture: no flygym/MuJoCo body simulation. The fly's body and the
// virtual park it flies through are simulated kinematically right here in
// the browser (position/heading integrated each frame from the
// connectome's own DN readout). The hero viewport is the fly's-eye camera
// flying through a procedural park; the real connectome (navis DN
// skeletons as volumetric tube fibers + soma InstancedMesh) sits beside
// it. Visual input flows the OTHER direction too: each few frames,
// brightness sampled from a tiny offscreen render of the fly's-eye view is
// sent to the backend as the optic-lobe sensory neurons' actual driving
// input (telemetry_server.py's "visual_input" command) — the real
// compound-eye pathway, not a constant drive.

import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Canvas, useFrame, useThree } from '@react-three/fiber'
import { Bounds, OrbitControls, Sky } from '@react-three/drei'
import * as THREE from 'three'

const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:8000'
const WS_URL = API_BASE.replace(/^http/, 'ws') + '/ws'
// Nodes-only sidecar (see run_simulation.py) — the dashboard never reads
// graph.edges, and on the full male-cns dataset edges are >90% of
// brain_graph.json's bytes (10.6M synapse-count triples, ~540MB total vs
// ~35MB of nodes). Fetching the raw file froze the tab parsing data we
// never use; this sidecar is regenerated by the backend on every load.
const GRAPH_URL = API_BASE + '/static/brain_graph_nodes.json'

const DN_COLOR = new THREE.Color('#ff6644')
const NEURON_COLOR = new THREE.Color('#4fa3ff')
const SPIKE_COLOR = new THREE.Color('#ffffff')
// Mushroom-body learning circuit — real neuPrint `class` populations, not
// superclass (see AGENTS.md "dopamine-modulated plasticity" entry: no
// kenyon_cell/mushroom_body superclass exists in this dataset).
const KC_COLOR = new THREE.Color('#7a5fd6')    // Kenyon cells — plastic (pre)
const MBON_COLOR = new THREE.Color('#d65fb0')  // MBONs — plastic (post)
const DAN_COLOR = new THREE.Color('#ffcc33')   // dopaminergic (PAM/PPL) — the reward/punishment signal itself
const LEARN_COLOR = new THREE.Color('#ff2fd0') // overlay for KC/MBON whose synapses have actually moved
const COLOR_DECAY = 0.85
const BRAIN_SCALE = 1 / 4000
const FLIGHT_SPEED = 7 // world units/sec of forward travel at thrust=1

function mulberry32(seed) {
  return function () {
    seed |= 0; seed = (seed + 0x6d2b79f5) | 0
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed)
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296
  }
}

// ---------------------------------------------------------------------
// Connectome layout (soma points) — same convention as before
// ---------------------------------------------------------------------

function useBrainLayout(graph) {
  return useMemo(() => {
    const nodes = graph.nodes.filter((n) => n.soma[0] !== null)
    const count = nodes.length
    const positions = new Float32Array(count * 3)
    const baseColors = new Float32Array(count * 3)
    const idIndex = new Map()

    let cx = 0, cy = 0, cz = 0
    for (const n of nodes) { cx += n.soma[0]; cy += n.soma[1]; cz += n.soma[2] }
    cx /= count; cy /= count; cz /= count

    nodes.forEach((n, i) => {
      positions[i * 3 + 0] = (n.soma[0] - cx) * BRAIN_SCALE
      positions[i * 3 + 1] = -(n.soma[2] - cz) * BRAIN_SCALE
      positions[i * 3 + 2] = (n.soma[1] - cy) * BRAIN_SCALE
      const c = n.is_dn ? DN_COLOR
        : n.class === 'Kenyon_Cell' ? KC_COLOR
        : n.class === 'MBON' ? MBON_COLOR
        : n.class === 'DAN' ? DAN_COLOR
        : NEURON_COLOR
      baseColors[i * 3 + 0] = c.r
      baseColors[i * 3 + 1] = c.g
      baseColors[i * 3 + 2] = c.b
      idIndex.set(n.id, i)
    })
    return { positions, baseColors, idIndex, count }
  }, [graph])
}

const _obj3d = new THREE.Object3D()
const _tmpColor = new THREE.Color()

function BrainInstances({ layout, spikeQueueRef, plasticWeightRef }) {
  const meshRef = useRef()
  const { positions, baseColors, idIndex, count } = layout

  useEffect(() => {
    const mesh = meshRef.current
    if (!mesh) return
    for (let i = 0; i < count; i++) {
      _obj3d.position.set(positions[i * 3], positions[i * 3 + 1], positions[i * 3 + 2])
      _obj3d.updateMatrix()
      mesh.setMatrixAt(i, _obj3d.matrix)
      _tmpColor.setRGB(baseColors[i * 3], baseColors[i * 3 + 1], baseColors[i * 3 + 2])
      mesh.setColorAt(i, _tmpColor)
    }
    mesh.instanceMatrix.needsUpdate = true
    if (mesh.instanceColor) mesh.instanceColor.needsUpdate = true
  }, [positions, baseColors, count])

  useFrame(() => {
    const mesh = meshRef.current
    if (!mesh || !mesh.instanceColor) return
    const colors = mesh.instanceColor.array
    for (let i = 0; i < count; i++) {
      const b = i * 3
      colors[b + 0] = baseColors[b + 0] + (colors[b + 0] - baseColors[b + 0]) * COLOR_DECAY
      colors[b + 1] = baseColors[b + 1] + (colors[b + 1] - baseColors[b + 1]) * COLOR_DECAY
      colors[b + 2] = baseColors[b + 2] + (colors[b + 2] - baseColors[b + 2]) * COLOR_DECAY
    }
    const spiking = spikeQueueRef.current
    if (spiking && spiking.length) {
      for (const bodyId of spiking) {
        const idx = idIndex.get(bodyId)
        if (idx === undefined) continue
        const b = idx * 3
        colors[b + 0] = SPIKE_COLOR.r; colors[b + 1] = SPIKE_COLOR.g; colors[b + 2] = SPIKE_COLOR.b
      }
      spikeQueueRef.current = null
    }
    // Reuses this exact same per-instance color-write mechanism (not a
    // separate rendering path) to show learning: KC/MBON somas whose
    // outgoing/incoming plastic synapses have measurably moved since
    // startup get pulled toward LEARN_COLOR, proportional to how much.
    const weights = plasticWeightRef && plasticWeightRef.current
    if (weights) {
      for (const key in weights) {
        const idx = idIndex.get(Number(key))
        if (idx === undefined) continue
        const amount = Math.min(1, weights[key] * 2) // |Δw/w0| of ~0.5 -> fully saturated
        if (amount <= 0.02) continue
        const b = idx * 3
        colors[b + 0] = colors[b + 0] + (LEARN_COLOR.r - colors[b + 0]) * amount
        colors[b + 1] = colors[b + 1] + (LEARN_COLOR.g - colors[b + 1]) * amount
        colors[b + 2] = colors[b + 2] + (LEARN_COLOR.b - colors[b + 2]) * amount
      }
    }
    mesh.instanceColor.needsUpdate = true
  })

  return (
    <instancedMesh ref={meshRef} args={[null, null, count]}>
      <icosahedronGeometry args={[0.06, 1]} />
      <meshBasicMaterial vertexColors toneMapped={false} transparent opacity={0.85} />
    </instancedMesh>
  )
}

// ---------------------------------------------------------------------
// Real DN morphology — navis skeletons as volumetric tube fibers
// (instanced oriented cylinders: one draw call, real 3D thickness)
// ---------------------------------------------------------------------

function useSegmentBuffer(url) {
  const [positions, setPositions] = useState(null)
  useEffect(() => {
    let cancelled = false
    fetch(url)
      .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(new Error(r.statusText))))
      .then((buf) => { if (!cancelled) setPositions(new Float32Array(buf)) })
      .catch(() => setPositions(null))
    return () => { cancelled = true }
  }, [url])
  return positions
}

const _p0 = new THREE.Vector3()
const _p1 = new THREE.Vector3()
const _dir = new THREE.Vector3()
const _mid = new THREE.Vector3()
const _quat = new THREE.Quaternion()
const _up = new THREE.Vector3(0, 1, 0)
const _fiberObj = new THREE.Object3D()
const FIBER_COLOR = new THREE.Color('#7fb8ff')

function TubeFibers({ positions, radius = 0.015 }) {
  const meshRef = useRef()
  const count = positions ? Math.floor(positions.length / 6) : 0

  useEffect(() => {
    const mesh = meshRef.current
    if (!mesh || !positions || count === 0) return
    for (let i = 0; i < count; i++) {
      const b = i * 6
      _p0.set(positions[b + 0], positions[b + 1], positions[b + 2])
      _p1.set(positions[b + 3], positions[b + 4], positions[b + 5])
      _dir.subVectors(_p1, _p0)
      const len = _dir.length()
      if (len < 1e-6) {
        _fiberObj.scale.set(0, 0, 0); _fiberObj.updateMatrix(); mesh.setMatrixAt(i, _fiberObj.matrix)
        continue
      }
      _dir.normalize()
      _mid.addVectors(_p0, _p1).multiplyScalar(0.5)
      _quat.setFromUnitVectors(_up, _dir)
      _fiberObj.position.copy(_mid)
      _fiberObj.quaternion.copy(_quat)
      _fiberObj.scale.set(radius, len, radius)
      _fiberObj.updateMatrix()
      mesh.setMatrixAt(i, _fiberObj.matrix)
    }
    mesh.instanceMatrix.needsUpdate = true
    mesh.computeBoundingSphere()
  }, [positions, count, radius])

  if (!positions || count === 0) return null
  return (
    <instancedMesh ref={meshRef} args={[null, null, count]} frustumCulled>
      <cylinderGeometry args={[1, 1, 1, 5, 1, false]} />
      <meshBasicMaterial color={FIBER_COLOR} toneMapped={false} transparent opacity={0.8} blending={THREE.AdditiveBlending} />
    </instancedMesh>
  )
}

function SkeletonFibers() {
  const finePositions = useSegmentBuffer(API_BASE + '/static/dn_skeleton_segments.bin')
  const coarsePositions = useSegmentBuffer(API_BASE + '/static/dn_skeleton_segments_coarse.bin')
  const { camera } = useThree()
  const [level, setLevel] = useState('coarse')
  const frameRef = useRef(0)

  useFrame(() => {
    frameRef.current += 1
    if (frameRef.current % 10 !== 0) return
    if (!finePositions || !coarsePositions) return
    const dist = camera.position.length()
    const want = dist < 8 ? 'fine' : 'coarse'
    if (want !== level) setLevel(want)
  })

  const positions = (level === 'fine' ? finePositions : coarsePositions) || coarsePositions || finePositions
  return <TubeFibers positions={positions} />
}

function BrainScene({ layout, spikeQueueRef, plasticWeightRef }) {
  return (
    <>
      <color attach="background" args={['#05070c']} />
      <ambientLight intensity={0.8} />
      <Bounds fit clip observe margin={1.35}>
        <SkeletonFibers />
        <BrainInstances layout={layout} spikeQueueRef={spikeQueueRef} plasticWeightRef={plasticWeightRef} />
      </Bounds>
      <OrbitControls enableDamping dampingFactor={0.08} rotateSpeed={0.5} makeDefault />
    </>
  )
}

// ---------------------------------------------------------------------
// Virtual park (procedural, no external assets)
// ---------------------------------------------------------------------

// ---------------------------------------------------------------------
// Procedural chunked park — the fix for the "trees disappear" bug
// (see AGENTS.md "Bug: static tree patch vs. unbounded flight" entry).
// Root cause, confirmed empirically via the TEMP DIAGNOSTIC panel and
// manual reset-flight testing (not assumed): Park() used to scatter its
// ~70 trees once, in a fixed disk of radius 6-76 around world origin
// (0,0), on a fixed 500x500 ground plane also centered on the origin.
// Nothing regenerated around the fly's *current* position — after
// several unpaused minutes the fly was measured ~309 units from origin
// (TEMP DIAGNOSTIC: flyPos), well outside both the tree disk and the
// ground plane's extent, and everything reappeared immediately after
// "reset flight" put the fly back at the origin. Not a rendering bug.
//
// Fix: an infinite deterministic field, chunked into fixed-size cells.
// Each cell's trees are derived from a hash of its own (cellX, cellZ)
// coordinates, so the same point in the world always has the same trees
// regardless of how many times that cell mounts/unmounts — no server
// round-trip, no stored world state, just a pure function of position.
// ---------------------------------------------------------------------

const CELL_SIZE = 24         // world units per cell; FLIGHT_SPEED=7 -> <1 cell/s at typical thrust
const VIEW_RADIUS_CELLS = 6  // ~144 units out, comfortably past the fog's far=140
const TREES_PER_CELL = 4

function cellSeed(cx, cz) {
  // Small integer hash (murmur-ish finalizer) so adjacent/negative cell
  // coordinates don't produce visibly-correlated seeds.
  let h = (cx * 374761393) ^ (cz * 668265263)
  h = Math.imul(h ^ (h >>> 15), 2246822519)
  h = Math.imul(h ^ (h >>> 13), 3266489917)
  h ^= h >>> 16
  return h >>> 0
}

function TreeCell({ cx, cz }) {
  // Each tree also draws a per-instance hue from the same seeded RNG (not
  // just scale/rotation as before) and a 3-layer stacked canopy instead of
  // one cone, for a fuller, less obviously-primitive silhouette — still
  // pure MeshBasicMaterial (no lights added: AGENTS.md documents
  // MeshStandardMaterial rendering everything black twice already in this
  // project for want of a matched light rig, and there's no browser tool
  // available this session to visually confirm a new one), so the "sense
  // of volume" comes from real per-tree/per-layer color variation instead.
  const trees = useMemo(() => {
    const rng = mulberry32(cellSeed(cx, cz))
    const arr = []
    for (let i = 0; i < TREES_PER_CELL; i++) {
      const lx = (rng() - 0.5) * CELL_SIZE
      const lz = (rng() - 0.5) * CELL_SIZE
      const s = 1 + rng() * 1.6
      const canopyHue = 95 + rng() * 40      // 95-135: yellow-green to blue-green
      const canopyLight = 22 + rng() * 10    // varied darkness per tree
      const trunkHue = 22 + rng() * 14
      arr.push([lx, lz, s, canopyHue, canopyLight, trunkHue])
    }
    return arr
  }, [cx, cz])

  const originX = cx * CELL_SIZE, originZ = cz * CELL_SIZE
  return (
    <>
      {trees.map(([lx, lz, s, canopyHue, canopyLight, trunkHue], i) => (
        <group key={i} position={[originX + lx, 0, originZ + lz]}>
          <mesh position={[0, s * 0.6, 0]}>
            <cylinderGeometry args={[0.14 * s, 0.2 * s, s * 1.2, 6]} />
            <meshBasicMaterial color={`hsl(${trunkHue}, 42%, 26%)`} toneMapped={false} />
          </mesh>
          {[0, 1, 2].map((layer) => (
            <mesh key={layer} position={[0, s * (1.1 + layer * 0.5), 0]}>
              <coneGeometry args={[(0.95 - layer * 0.22) * s, 1.1 * s, 8]} />
              {/* each layer a touch lighter going up -- cheap fake ambient occlusion */}
              <meshBasicMaterial
                color={`hsl(${canopyHue}, 40%, ${canopyLight + layer * 4}%)`}
                toneMapped={false}
              />
            </mesh>
          ))}
        </group>
      ))}
    </>
  )
}

// Ground: one large plane, re-centered under the fly every frame rather
// than chunked — much simpler than tiling terrain, and at 1200 units wide
// it takes several minutes of continuous max-thrust flight in one
// direction to ever approach an edge, which combined with re-centering
// means it effectively never runs out for any realistic session length.
function Ground({ flightStateRef }) {
  const meshRef = useRef()
  useFrame(() => {
    const s = flightStateRef.current
    if (meshRef.current) meshRef.current.position.set(s.x, 0, s.z)
  })
  return (
    <mesh ref={meshRef} rotation={[-Math.PI / 2, 0, 0]}>
      <planeGeometry args={[1200, 1200]} />
      <meshBasicMaterial color="#4f9142" toneMapped={false} />
    </mesh>
  )
}

function ParkChunks({ flightStateRef, debugRef }) {
  const [activeCells, setActiveCells] = useState(() => [])
  const frameRef = useRef(0)
  const lastKeyRef = useRef('')

  useFrame(() => {
    frameRef.current++
    if (frameRef.current % 15 !== 0) return // recompute ~4x/s, not every frame
    const s = flightStateRef.current
    const centerCx = Math.round(s.x / CELL_SIZE)
    const centerCz = Math.round(s.z / CELL_SIZE)
    const key = `${centerCx},${centerCz}`
    if (key === lastKeyRef.current) return // fly hasn't crossed a cell boundary; no diff needed
    lastKeyRef.current = key

    const cells = []
    for (let dx = -VIEW_RADIUS_CELLS; dx <= VIEW_RADIUS_CELLS; dx++) {
      for (let dz = -VIEW_RADIUS_CELLS; dz <= VIEW_RADIUS_CELLS; dz++) {
        cells.push([centerCx + dx, centerCz + dz])
      }
    }
    setActiveCells(cells)
    if (debugRef) {
      debugRef.current = {
        ...debugRef.current,
        activeCellCount: cells.length,
        nearbyTreeCount: cells.length * TREES_PER_CELL,
        centerCell: [centerCx, centerCz],
      }
    }
  })

  return (
    <>
      {activeCells.map(([cx, cz]) => <TreeCell key={`${cx},${cz}`} cx={cx} cz={cz} />)}
    </>
  )
}

function Park({ flightStateRef, debugRef }) {
  return (
    <>
      {/* drei's <Sky> is a self-contained atmospheric shader (Preetham sky
          model) — not lit by scene lights, so it's safe to use without the
          MeshStandardMaterial light-rig problem documented in AGENTS.md.
          Replaces the flat background color for real atmospheric depth. */}
      <Sky sunPosition={[100, 18, 60]} turbidity={3} rayleigh={1.1} mieCoefficient={0.006} />
      <fog attach="fog" args={['#bcdcef', 25, 140]} />
      {/* Everything below is still MeshBasicMaterial deliberately, same
          lesson as the brain view: it's self-illuminated and ignores scene
          lighting entirely, so nothing in the park can end up
          invisible/black because of a lighting-rig mismatch — only ever a
          risk in a StandardMaterial scene, never here. Volume/shading now
          comes from real per-instance/per-layer color variation (see
          TreeCell) instead of actual lights, since there's no browser tool
          available this session to visually confirm a new light rig. */}
      <Ground flightStateRef={flightStateRef} />
      <ParkChunks flightStateRef={flightStateRef} debugRef={debugRef} />
    </>
  )
}

// A real (if procedural, no external glTF fetched) wing outline instead of
// a flat rectangle: a teardrop silhouette via quadratic Bezier curves,
// built once and shared by both wings (mirrored via negative X scale on
// the right one) rather than duplicated.
function useWingGeometry() {
  return useMemo(() => {
    const shape = new THREE.Shape()
    shape.moveTo(0, 0)
    shape.quadraticCurveTo(0.12, 0.09, 0.4, 0.12)
    shape.quadraticCurveTo(0.62, 0.14, 0.58, 0.02)
    shape.quadraticCurveTo(0.54, -0.07, 0.32, -0.05)
    shape.quadraticCurveTo(0.12, -0.03, 0, 0)
    return new THREE.ShapeGeometry(shape)
  }, [])
}

// A visible fly body so there's something to actually watch move through
// the park (a pure first-person view showed nothing at all — just sky and
// distant trees drifting, which read as "an empty screen"). Segmented
// thorax/abdomen/head + real compound eyes + curved wing silhouettes,
// replacing the original capsule-and-two-rectangles placeholder — still
// built from primitives (no external asset dependency/licensing to
// manage), just with real fly topology instead of "programmer art".
function FlyAvatar({ flightStateRef }) {
  const groupRef = useRef()
  const wingGeo = useWingGeometry()
  useFrame(() => {
    const s = flightStateRef.current
    if (!groupRef.current) return
    groupRef.current.position.set(s.x, s.y, s.z)
    groupRef.current.rotation.y = s.heading
  })
  return (
    <group ref={groupRef}>
      {/* thorax */}
      <mesh scale={[0.16, 0.15, 0.22]}>
        <sphereGeometry args={[1, 10, 8]} />
        <meshBasicMaterial color="#8a5a2a" toneMapped={false} />
      </mesh>
      {/* abdomen: tapered, trailing behind the thorax */}
      <mesh position={[0, -0.015, -0.34]} rotation={[Math.PI / 2, 0, 0]} scale={[0.13, 0.13, 0.36]}>
        <coneGeometry args={[1, 1.7, 10]} />
        <meshBasicMaterial color="#caa14a" toneMapped={false} />
      </mesh>
      {/* head */}
      <mesh position={[0, 0.015, 0.22]} scale={[0.1, 0.1, 0.1]}>
        <sphereGeometry args={[1, 10, 8]} />
        <meshBasicMaterial color="#6b4a2f" toneMapped={false} />
      </mesh>
      {/* compound eyes — the single most recognizable fly feature; two
          spheres instead of one flat red disc */}
      <mesh position={[-0.085, 0.025, 0.27]}>
        <sphereGeometry args={[0.065, 8, 8]} />
        <meshBasicMaterial color="#c0392b" toneMapped={false} />
      </mesh>
      <mesh position={[0.085, 0.025, 0.27]}>
        <sphereGeometry args={[0.065, 8, 8]} />
        <meshBasicMaterial color="#c0392b" toneMapped={false} />
      </mesh>
      {/* wings */}
      <mesh position={[-0.04, 0.1, -0.02]} rotation={[0, 0.25, 0.18]} geometry={wingGeo}>
        <meshBasicMaterial color="#eaf6ff" transparent opacity={0.55} toneMapped={false} side={THREE.DoubleSide} />
      </mesh>
      <mesh position={[0.04, 0.1, -0.02]} rotation={[0, -0.25, -0.18]} scale={[-1, 1, 1]} geometry={wingGeo}>
        <meshBasicMaterial color="#eaf6ff" transparent opacity={0.55} toneMapped={false} side={THREE.DoubleSide} />
      </mesh>
    </group>
  )
}

// ---------------------------------------------------------------------
// Kinematic flight: position/heading integrated each frame from the
// server's DN-derived (thrust, yaw_rate) command. No physics engine —
// this is why there's no physics-timestep bottleneck anymore.
// ---------------------------------------------------------------------

// Deterministic tree lookup for collision testing — recomputes a cell's
// trees on demand via the exact same cellSeed/mulberry32 math TreeCell
// uses, rather than trying to read TreeCell's mounted React state from
// outside it. Cheap (a handful of RNG draws per nearby cell per frame).
function treesInCell(cx, cz) {
  const rng = mulberry32(cellSeed(cx, cz))
  const arr = []
  for (let i = 0; i < TREES_PER_CELL; i++) {
    const lx = (rng() - 0.5) * CELL_SIZE
    const lz = (rng() - 0.5) * CELL_SIZE
    const s = 1 + rng() * 1.6
    arr.push([cx * CELL_SIZE + lx, cz * CELL_SIZE + lz, s])
  }
  return arr
}

function FlightRig({ flightCmdRef, flightStateRef, trailRef, sendVisual, debugRef, onCollision }) {
  const { camera, gl, scene } = useThree()
  const rtRef = useRef()
  const eyeCamRef = useRef()
  const lookTarget = useRef(new THREE.Vector3())
  const frameRef = useRef(0)
  const collisionCooldownRef = useRef(0)

  useEffect(() => {
    rtRef.current = new THREE.WebGLRenderTarget(16, 8)
    // Separate, never-displayed first-person camera: this is what the fly
    // itself "sees" (used only for the compound-eye brightness sample
    // below). The camera the user actually watches is a third-person
    // chase cam, set from the main `camera` further down — otherwise a
    // pure first-person view over open park terrain reads as "an empty
    // screen with nothing on it", which is exactly what was reported.
    eyeCamRef.current = new THREE.PerspectiveCamera(100, 2, 0.1, 300)
    return () => rtRef.current.dispose()
  }, [])

  useFrame((_, delta) => {
    const cmd = flightCmdRef.current
    const s = flightStateRef.current
    const dt = Math.min(delta, 0.05) // guard against huge deltas on tab refocus
    s.heading += cmd.yaw_rate * dt
    const speed = cmd.thrust * FLIGHT_SPEED
    s.x += Math.sin(s.heading) * speed * dt
    s.z += Math.cos(s.heading) * speed * dt
    s.y = 3 + Math.sin(performance.now() * 0.001 + s.heading) * 0.25 // gentle cosmetic bob

    // Third-person chase camera: behind and above the fly, looking at it —
    // so there's always a visible fly body moving through visible terrain.
    const behind = 3.5, up = 1.8
    camera.position.set(
      s.x - Math.sin(s.heading) * behind,
      s.y + up,
      s.z - Math.cos(s.heading) * behind,
    )
    lookTarget.current.set(s.x, s.y, s.z)
    camera.lookAt(lookTarget.current)

    // Obstacle-avoidance learning task: check the fly's own cell + its 8
    // neighbors for a real tree collision (same deterministic tree field
    // FlightRig — and ParkChunks — both derive from cellSeed/mulberry32,
    // so this can't drift out of sync with what's actually rendered). A
    // 1.5s cooldown after firing avoids spamming force_spike every frame
    // while the fly sits inside a tree's collision radius.
    if (onCollision) {
      collisionCooldownRef.current = Math.max(0, collisionCooldownRef.current - dt)
      if (collisionCooldownRef.current <= 0) {
        const fcx = Math.round(s.x / CELL_SIZE), fcz = Math.round(s.z / CELL_SIZE)
        outer:
        for (let dx = -1; dx <= 1; dx++) {
          for (let dz = -1; dz <= 1; dz++) {
            for (const [tx, tz, ts] of treesInCell(fcx + dx, fcz + dz)) {
              const ddx = s.x - tx, ddz = s.z - tz
              const collideDist = 0.35 * ts + 0.15 // canopy/trunk radius + fly body
              if (ddx * ddx + ddz * ddz < collideDist * collideDist) {
                onCollision()
                collisionCooldownRef.current = 1.5
                break outer
              }
            }
          }
        }
      }
    }

    // TEMP DIAGNOSTIC (Prompt 1 investigation) — cheap ref mutation, no
    // re-render; Dashboard polls this on an interval to display it.
    if (debugRef) {
      debugRef.current = {
        ...debugRef.current,
        camPos: [camera.position.x, camera.position.y, camera.position.z].map((v) => +v.toFixed(2)),
        flyPos: [s.x, s.y, s.z].map((v) => +v.toFixed(2)),
        heading: +s.heading.toFixed(3),
        trailLen: trailRef.current.length,
      }
    }

    frameRef.current++
    if (frameRef.current % 5 === 0) {
      trailRef.current.push([s.x, s.z])
      if (trailRef.current.length > 800) trailRef.current.shift()
    }

    // Compound-eye sampling: render the fly's own first-person view (the
    // separate eyeCam, not the chase cam the user sees) into a tiny
    // offscreen target and split it into left/right average brightness —
    // the actual visual input sent to the optic-lobe sensory neurons.
    if (frameRef.current % 3 === 0 && rtRef.current && eyeCamRef.current) {
      const eyeCam = eyeCamRef.current
      eyeCam.position.set(s.x, s.y, s.z)
      eyeCam.rotation.set(0, s.heading, 0)
      eyeCam.updateMatrixWorld()
      const rt = rtRef.current
      gl.setRenderTarget(rt)
      gl.render(scene, eyeCam)
      gl.setRenderTarget(null)
      const buf = new Uint8Array(16 * 8 * 4)
      gl.readRenderTargetPixels(rt, 0, 0, 16, 8, buf)
      let leftSum = 0, rightSum = 0
      for (let row = 0; row < 8; row++) {
        for (let col = 0; col < 16; col++) {
          const idx = (row * 16 + col) * 4
          const lum = (buf[idx] + buf[idx + 1] + buf[idx + 2]) / (3 * 255)
          if (col < 8) leftSum += lum; else rightSum += lum
        }
      }
      sendVisual(leftSum / 64, rightSum / 64)
    }
  })

  return null
}

function ParkScene({ flightCmdRef, flightStateRef, trailRef, sendVisual, debugRef, onCollision }) {
  return (
    <>
      <Park flightStateRef={flightStateRef} debugRef={debugRef} />
      <FlyAvatar flightStateRef={flightStateRef} />
      <FlightRig
        flightCmdRef={flightCmdRef} flightStateRef={flightStateRef}
        trailRef={trailRef} sendVisual={sendVisual} debugRef={debugRef} onCollision={onCollision}
      />
    </>
  )
}

// ---------------------------------------------------------------------
// Control panel
// ---------------------------------------------------------------------

function ControlPanel({ graph, sendCmd, paused, sensoryDrive, noiseStd, connected, learningEnabled }) {
  const [localDrive, setLocalDrive] = useState(1.0)
  const [localNoise, setLocalNoise] = useState(0.0)

  useEffect(() => { if (sensoryDrive !== null) setLocalDrive(sensoryDrive) }, [sensoryDrive])
  useEffect(() => { if (noiseStd !== null) setLocalNoise(noiseStd) }, [noiseStd])

  const dnLeftIds = useMemo(() => graph.nodes.filter((n) => n.is_dn && n.soma_side === 'L').map((n) => n.id), [graph])
  const dnRightIds = useMemo(() => graph.nodes.filter((n) => n.is_dn && n.soma_side === 'R').map((n) => n.id), [graph])
  const sensoryIds = useMemo(() => graph.nodes.filter((n) => (n.superclass || '').includes('sensory')).map((n) => n.id), [graph])
  const pplIds = useMemo(() => graph.nodes.filter((n) => n.class === 'DAN' && (n.type || '').startsWith('PPL')).map((n) => n.id), [graph])
  const pamIds = useMemo(() => graph.nodes.filter((n) => n.class === 'DAN' && (n.type || '').startsWith('PAM')).map((n) => n.id), [graph])

  const sample = (ids, n) => {
    if (ids.length <= n) return ids
    const out = []; const used = new Set()
    while (out.length < n) {
      const i = Math.floor(Math.random() * ids.length)
      if (used.has(i)) continue
      used.add(i); out.push(ids[i])
    }
    return out
  }

  return (
    <div className="control-panel panel">
      <div className="title">brain controls</div>
      <div className="control-row">
        <button className={connected ? 'btn ok' : 'btn bad'} disabled>
          {connected ? '● connected' : '○ disconnected'}
        </button>
      </div>
      <div className="control-row buttons">
        <button className="btn primary" onClick={() => sendCmd({ cmd: paused ? 'resume' : 'pause' })}>
          {paused ? '▶ resume' : '⏸ pause'}
        </button>
        <button className="btn" onClick={() => sendCmd({ cmd: 'reset' })}>⟲ reset flight</button>
      </div>
      <label className="slider-label">
        sensory drive: {localDrive.toFixed(2)}
        <input type="range" min="0" max="3" step="0.05" value={localDrive}
          onChange={(e) => { const v = parseFloat(e.target.value); setLocalDrive(v); sendCmd({ cmd: 'set_params', sensory_drive: v }) }} />
      </label>
      <label className="slider-label">
        noise σ: {localNoise.toFixed(2)}
        <input type="range" min="0" max="1.5" step="0.02" value={localNoise}
          onChange={(e) => { const v = parseFloat(e.target.value); setLocalNoise(v); sendCmd({ cmd: 'set_params', noise_std: v }) }} />
      </label>
      <div className="title" style={{ marginTop: 10 }}>manual spike injection</div>
      <div className="control-row buttons">
        <button className="btn" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: sample(sensoryIds, 80) })}>stimulate sensory</button>
      </div>
      <div className="control-row buttons">
        <button className="btn dn-left" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: sample(dnLeftIds, 40) })}>fire DN · L</button>
        <button className="btn dn-right" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: sample(dnRightIds, 40) })}>fire DN · R</button>
      </div>

      <div className="title" style={{ marginTop: 10 }}>mushroom-body learning (KC→MBON)</div>
      <div className="control-row buttons">
        <button
          className={learningEnabled ? 'btn ok' : 'btn'}
          onClick={() => sendCmd({ cmd: 'set_learning', enabled: !learningEnabled })}
        >
          {learningEnabled ? '● learning ON — click to freeze' : '○ learning off — click to enable'}
        </button>
      </div>
      <div className="control-row buttons">
        <button className="btn dn-left" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: pplIds })}>
          fire PPL (aversive)
        </button>
        <button className="btn dn-right" onClick={() => sendCmd({ cmd: 'inject_spike', body_ids: sample(pamIds, 60) })}>
          fire PAM (appetitive)
        </button>
      </div>
    </div>
  )
}

function Minimap({ trailRef }) {
  const canvasRef = useRef()
  useEffect(() => {
    let raf
    const draw = () => {
      const canvas = canvasRef.current
      if (canvas) {
        const ctx = canvas.getContext('2d')
        const w = canvas.width, h = canvas.height
        ctx.fillStyle = 'rgba(5,7,12,0.35)'
        ctx.fillRect(0, 0, w, h)
        const trail = trailRef.current
        if (trail.length > 1) {
          // Fly-centered, not world-origin-centered — same class of bug as
          // the static tree patch (see Park/ParkChunks above and the
          // AGENTS.md entry): drawing at `w/2 + x*3` put the trail off the
          // 150x150 canvas entirely once the fly was more than ~25 world
          // units from the origin, which after any real flight duration it
          // always is. Anchor on the fly's own current position instead.
          const [fx, fz] = trail[trail.length - 1]
          ctx.strokeStyle = '#4fa3ff'; ctx.lineWidth = 1.5
          ctx.beginPath()
          trail.forEach(([x, z], i) => {
            const px = w / 2 + (x - fx) * 3, py = h / 2 - (z - fz) * 3
            if (i === 0) ctx.moveTo(px, py); else ctx.lineTo(px, py)
          })
          ctx.stroke()
          ctx.fillStyle = '#ff6644'
          ctx.beginPath(); ctx.arc(w / 2, h / 2, 3.5, 0, 2 * Math.PI); ctx.fill()
        }
      }
      raf = requestAnimationFrame(draw)
    }
    raf = requestAnimationFrame(draw)
    return () => cancelAnimationFrame(raf)
  }, [trailRef])
  return <canvas ref={canvasRef} width={150} height={150} className="minimap" />
}

// ---------------------------------------------------------------------
// Main dashboard
// ---------------------------------------------------------------------

export default function Dashboard() {
  const [graph, setGraph] = useState(null)
  const [error, setError] = useState(null)
  const [connected, setConnected] = useState(false)
  const [stats, setStats] = useState({
    t: 0, thrust: 0.5, yawRate: 0, nSpiking: 0,
    paused: false, sensoryDrive: null, noiseStd: null, visualL: 0.5, visualR: 0.5,
    rewardSignal: 0, cumulativeReward: 0, learningEnabled: false,
  })

  const spikeQueueRef = useRef(null)
  const trailRef = useRef([])
  const wsRef = useRef(null)
  const flightCmdRef = useRef({ thrust: 0.5, yaw_rate: 0 })
  const flightStateRef = useRef({ x: 0, y: 3, z: 0, heading: 0 })
  // Sent only every ~30 broadcast ticks (bandwidth — see telemetry_server.py);
  // kept as a plain ref holding the last-received map so BrainInstances
  // always has *something* to read even on ticks that didn't carry it.
  const plasticWeightRef = useRef(null)

  // TEMP DIAGNOSTIC (Prompt 1 investigation) — plain ref written every
  // frame by Park/FlightRig, polled here on an interval (not per-frame, to
  // avoid re-rendering the whole tree 60x/sec) and shown as an always-on
  // HTML overlay. This is plain React/DOM text, independent of whatever
  // WebGL is or isn't doing, so it isolates "did the JS logic run
  // correctly" from "did the GPU actually draw it".
  const debugRef = useRef({})
  const [debugDisplay, setDebugDisplay] = useState({})
  useEffect(() => {
    const id = setInterval(() => setDebugDisplay({ ...debugRef.current }), 500)
    return () => clearInterval(id)
  }, [])

  useEffect(() => {
    fetch(GRAPH_URL)
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(`${r.status} ${r.statusText}`))))
      .then(setGraph)
      .catch((e) => setError(`Failed to load brain_graph.json from ${GRAPH_URL}: ${e.message}`))
  }, [])

  useEffect(() => {
    let ws, retryTimer, closedByUs = false
    const connect = () => {
      ws = new WebSocket(WS_URL)
      wsRef.current = ws
      ws.onopen = () => setConnected(true)
      ws.onclose = () => { setConnected(false); if (!closedByUs) retryTimer = setTimeout(connect, 1500) }
      ws.onerror = () => ws.close()
      ws.onmessage = (evt) => {
        const d = JSON.parse(evt.data)
        spikeQueueRef.current = d.spiking_ids
        flightCmdRef.current = { thrust: d.thrust, yaw_rate: d.yaw_rate }
        if (d.plastic_weight_changes) plasticWeightRef.current = d.plastic_weight_changes
        setStats({
          t: d.t, thrust: d.thrust, yawRate: d.yaw_rate, nSpiking: d.spiking_ids.length,
          paused: !!d.paused, sensoryDrive: d.sensory_drive ?? null, noiseStd: d.noise_std ?? null,
          visualL: d.visual_L ?? 0.5, visualR: d.visual_R ?? 0.5,
          rewardSignal: d.reward_signal ?? 0, cumulativeReward: d.cumulative_reward ?? 0,
          learningEnabled: !!d.learning_enabled,
        })
      }
    }
    connect()
    return () => { closedByUs = true; clearTimeout(retryTimer); ws?.close() }
  }, [])

  const sendCmd = useCallback((cmd) => {
    const ws = wsRef.current
    if (ws && ws.readyState === WebSocket.OPEN) ws.send(JSON.stringify(cmd))
    if (cmd.cmd === 'reset') {
      flightStateRef.current = { x: 0, y: 3, z: 0, heading: 0 }
      trailRef.current = []
    }
  }, [])

  const sendVisual = useCallback((left, right) => {
    const ws = wsRef.current
    if (ws && ws.readyState === WebSocket.OPEN) {
      ws.send(JSON.stringify({ cmd: 'visual_input', left, right }))
    }
  }, [])

  const layout = useBrainLayout(graph ?? { nodes: [], edges: [] })
  // Obstacle-avoidance task (Prompt 2, step 5): a real tree collision fires
  // the real PPL (aversive) population via the same inject_spike path the
  // manual control-panel buttons use — no separate backend mechanism.
  const pplIds = useMemo(
    () => (graph?.nodes ?? []).filter((n) => n.class === 'DAN' && (n.type || '').startsWith('PPL')).map((n) => n.id),
    [graph],
  )
  const onCollision = useCallback(() => {
    sendCmd({ cmd: 'inject_spike', body_ids: pplIds })
  }, [sendCmd, pplIds])

  if (error) return <div className="panel error">{error}</div>
  if (!graph) return <div className="panel">Loading brain_graph.json...</div>

  return (
    <div className="dashboard-root">
      {/* HERO: fly's-eye view flying through the park */}
      <div className="hero-fly">
        <Canvas camera={{ fov: 60, position: [0, 4.8, -3.5] }}>
          <ParkScene
            flightCmdRef={flightCmdRef} flightStateRef={flightStateRef} trailRef={trailRef}
            sendVisual={sendVisual} debugRef={debugRef} onCollision={onCollision}
          />
        </Canvas>
        <div className="hero-overlay panel" style={{ top: 140, left: 16, fontSize: 10, opacity: 0.85 }}>
          <div className="title">TEMP DIAGNOSTIC (Prompt 1)</div>
          <div>nearby trees: {debugDisplay.nearbyTreeCount ?? '—'} (active cells: {debugDisplay.activeCellCount ?? '—'}, center: {JSON.stringify(debugDisplay.centerCell ?? null)})</div>
          <div>flyPos: {JSON.stringify(debugDisplay.flyPos ?? null)}  heading: {debugDisplay.heading ?? '—'}</div>
          <div>camPos: {JSON.stringify(debugDisplay.camPos ?? null)}</div>
          <div>trailRef.length: {debugDisplay.trailLen ?? '—'}</div>
        </div>
        <div className="hero-overlay top-left panel">
          <div className="title">vision-first flight / virtual park</div>
          <div>t = {stats.t.toFixed(3)}s{stats.paused ? '  ·  PAUSED' : ''}</div>
          <div>thrust {stats.thrust.toFixed(2)} · yaw {stats.yawRate.toFixed(2)}</div>
        </div>
        <div className="hero-overlay bottom-left panel">
          <div className="title">position (top-down)</div>
          <Minimap trailRef={trailRef} />
        </div>
        <div className="hero-overlay top-right panel">
          <div className="title">compound eye input</div>
          <DriveBar label="L" value={stats.visualL} range={[0, 1]} />
          <DriveBar label="R" value={stats.visualR} range={[0, 1]} />
          <div>spiking this tick: {stats.nSpiking}</div>
        </div>
        <div className="hero-overlay panel" style={{ top: 140, right: 16, minWidth: 170 }}>
          <div className="title">mushroom-body learning</div>
          <div>{stats.learningEnabled ? '● learning ON' : '○ learning off'}</div>
          <DriveBar label="reward" value={stats.rewardSignal} range={[-0.2, 0.2]} />
          <div>cumulative: {stats.cumulativeReward.toFixed(2)}</div>
        </div>
      </div>

      <div className="side-col">
        <div className="brain-view">
          <Canvas camera={{ position: [0, 0, 6], fov: 50 }}>
            <BrainScene layout={layout} spikeQueueRef={spikeQueueRef} plasticWeightRef={plasticWeightRef} />
          </Canvas>
          <div className="hud top-left panel small">
            <div className="title">male-cns:v1.0 — {graph.meta.node_count.toLocaleString()} neurons</div>
            <div>DNs: {graph.meta.dn_count.toLocaleString()} · edges: {graph.meta.edge_count.toLocaleString()}</div>
          </div>
        </div>
        <ControlPanel
          graph={graph} sendCmd={sendCmd} paused={stats.paused}
          sensoryDrive={stats.sensoryDrive} noiseStd={stats.noiseStd} connected={connected}
          learningEnabled={stats.learningEnabled}
        />
      </div>
    </div>
  )
}

function DriveBar({ label, value, range = [-0.5, 1.5] }) {
  const [lo, hi] = range
  const pct = Math.max(0, Math.min(100, ((value - lo) / (hi - lo)) * 100))
  return (
    <div className="drive-bar">
      <span>{label}</span>
      <div className="drive-bar-track"><div className="drive-bar-fill" style={{ width: `${pct}%` }} /></div>
      <span>{value.toFixed(2)}</span>
    </div>
  )
}
